[package]
name = "nekocalc"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
authors = ["Avery R. <contact@nekodjin.org>"]
repository = "https://github.com/nekodjin/nekocalc"
description = "A Calculator"

[dependencies]
logos = "0.12"
ariadne = "0.1"
chumsky = "0.8"
